"""empty message

Revision ID: f50df0d3bec1
Revises: 
Create Date: 2017-02-12 11:17:42.192027

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f50df0d3bec1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('main',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('shell_url', sa.String(), nullable=True),
    sa.Column('shell_type', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('commands',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('shell_id', sa.Integer(), nullable=True),
    sa.Column('shell_history', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['shell_id'], ['main.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('shellinfo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('shell_id', sa.Integer(), nullable=True),
    sa.Column('shell_os', sa.String(), nullable=True),
    sa.Column('shell_webserver_type', sa.String(), nullable=True),
    sa.Column('shell_users', sa.String(), nullable=True),
    sa.Column('shell_passwords', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['shell_id'], ['main.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('shellinfo')
    op.drop_table('commands')
    op.drop_table('main')
    # ### end Alembic commands ###
